---
# Tasks specific for RedHat systems

- name: "RedHat | Set some facts"
  set_fact:
    ansible_distribution: centos
  when: ansible_distribution == "RedHat"

- name: "RedHat | Install atomicorp repo"
  yum:
    name: "{{ ossec_download_url }}"
    disable_gpg_check: "{{ ossec_server_disable_gpgkey }}"
    state: present

- name: "RedHat | Install epel repo rpm key"
  rpm_key:
    state: present
    key: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"


- name: "RedHat | Install epel repo"
  yum:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present
