---
- name: Converge
  hosts: server
  pre_tasks:
    - name: "Get ip Ossec Server"
      shell: grep $(hostname) /etc/hosts | awk '{print $1}' | sort | head -n 1
      register: ossec_server
      changed_when: False

    - name: "Get ossec_server_client_auth"
      shell: cat /var/ossec/logs/ossec.log | grep "Random password chosen for agent authentication:" | tail -n1 | cut -d':' -f4 | awk '{$1=$1};1'
      register: ossec_server_client_auth
      changed_when: False

- hosts: all:!server
  roles:
    - role: ansible-ossec-agent
      ossec_server_name: ossec-server-centos
      ossec_server_ip: "{{ hostvars['ossec-server-centos']['ossec_server']['stdout'] }}"
      ossec_server_fqdn: ossec-server-centos
      ossec_agent_client_pass: "{{ hostvars['ossec-server-centos']['ossec_server_client_auth']['stdout'] }}"
