---
- name: Converge
  hosts: server
  pre_tasks:
    - name: "Get ip Ossec Server"
      shell: grep $(hostname) /etc/hosts | awk '{print $1}' | sort | head -n 2 | tail -n 1
      register: ossec_server
      changed_when: False

- hosts: all:!server
  roles:
    - role: ansible-ossec-agent
      ossec_server_name: ossec-server-centos
      ossec_server_ip: "{{ hostvars['ossec-server-centos']['ossec_server']['stdout'] }}"
      ossec_server_fqdn: "{{ hostvars['ossec-server-centos']['ossec_server']['stdout'] }}"
